branch-defaults:
  master:
    environment: garms-express-env
    group_suffix: null
global:
  application_name: garms-express-1
  branch: null
  default_ec2_keyname: nn-keys
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
